language: php

php:
    - 7.1
    - 7.2

env:
    matrix:
        - SYMFONY_VERSION="3.4.*"
        - SYMFONY_VERSION="4.0.*"
        - SYMFONY_VERSION="4.1.*"

cache:
    directories:
        - ~/.composer/cache/files

before_install:
    - phpenv config-rm xdebug.ini || true
    - echo "memory_limit=4096M" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

install:
    - composer require "symfony/symfony:${SYMFONY_VERSION}" --no-interaction --no-update
    - composer update --no-interaction --prefer-dist

script:
    - composer validate --strict

    - vendor/bin/phpspec run --format dot -vvv --no-interaction
    - vendor/bin/phpunit
